# Generated by Django 5.2.5 on 2025-08-29 15:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=10, verbose_name='Tipo de Mídia')),
                ('file', models.FileField(upload_to='gallery/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov', 'webm'])], verbose_name='Arquivo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/%Y/%m/%d/', verbose_name='Miniatura')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Upload')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Item de Mídia',
                'verbose_name_plural': 'Itens de Mídia',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
